### ISSUE TITLE
Is there a way to recalculate just one memoized attribute?

### ISSUE THREAD

**Issue by artsyca** [tycooon/memery#18]
I know that the prevailing `memoized_attribute(true)` approach is somewhat flaky but is there a way to recalculate a given memoized property without expiring the entire cache so to speak?

As well I apologize if my knowledge of memery is somewhat limited but does it memoize functions that accept arguments?

**Comment by tycooon** [comment]
Skipping memoization is covered in the Readme here: https://github.com/tycooon/memery#difference-with-other-gems.
In your case you can either provide an empty block or to create an extra unmemoized method and use it in the memoized one.

Functions with arguments are supported, that's covered in the Readme as well :)

**Comment by artsyca** [comment]
Yes, that's well understood, but apart from clearing the entire cache, there's no way to recalculate a memoized value, is there?

**Comment by artsyca** [comment]
The readme could be more explicit about the memoization of functions with arguments, it's only a passing reference which is why I'm asking to be certain

**Comment by tycooon** [comment]
> Yes, that's well understood, but apart from clearing the entire cache, there's no way to recalculate (and rememoize) a memoized value, is there?

Right now there is not. I guess we could add an optional argument to `clear_memery_cache!` with the method names.

**Comment by artsyca** [comment]
It's very kind of you to take this into consideration --

**Comment by artsyca** [comment]
It's not particularly pressing in my particular case -- I'm using memoization to cache a rather expensive API request and need to re-query after performing an update operation.. expiring the whole cache does fit into my use case but I was more curious about best practices. Welcome to close the ticket and consider this feature at your convenience

**Comment by tycooon** [comment]
> The readme could be more explicit about the memoization of functions with arguments, it's only a passing reference which is why I'm asking to be certain

Oops, I just added the example here https://github.com/tycooon/memery/commit/bce494397da843dc273b68ce4386da3c491f64b4.
