### ISSUE TITLE
Caching of methods with default arguments

### ISSUE THREAD

**Issue by doits** [tycooon/memery#40]
It looks like default method arguments are not cached separately if they change implicitly, take this for example:

```rb
Object.include Memery

I18n = Struct.new(:locale).new(:en)

def test_method(locale: I18n.locale)
  locale
end

Object.memoize :test_method

test_method
# => :en, correct

test_method(locale: :fr)
# => :fr, correct

I18n.locale = :fr

test_method
# => :en, wrong, should be :fr
```

Didn't have a chance to look at the code yet, but wanted to raise the issue before I forget :-)

**Comment by tycooon** [comment]
You should only memoize the method in case you expect to always get the same output for the same input. If this condition doesn't apply you simply can not memoize the method. For example, you probably should not memoize the method that uses current time inside of it (since it probably will change next time you call the method). In your case `test_method` is using `I18n.locale` which might change. So here are the options I see here:

1. Just don't memoize the method.
2. Remove the default value from the method and always explicitly pass the value from the caller.

**Comment by doits** [comment]
Yes, it seems to be a matter of definition what "same input" means. I assumed that a different default argument is "*different* input", even if the method call stays the same (only `test_method`).

So in fact Memory treats the method as if it was written like this:

```rb
def test_method(locale: nil)
  locale ||= I18n.locale

  locale
end
```

I'd still argue that having a changing default argument in the method definition should be treated differently by Memery, because it feels more like "it just works" and is what at least I'd expect.

Feel free to close this issue if you don't plan to support default arguments this way (I'm OK with this). I could create a PR to put this into the Readme then at least, if you'd like.

---

As a quick fix I just worked it around like this:

```rb
def test_method(locale: I18n.locale)
  test_method_memery(locale)
end

private

def test_method_memery(locale)
  locale
end
memoize :test_method_memery
```

So my code can still rely on simply calling `test_method` without arguments.

**Comment by tycooon** [comment]
> So in fact Memory treats the method as if it was written like this:

Exactly, that's how Ruby works and I don't think it's possible to change that. The default arguments' values are evaluated inside the method so we can't know their value without actually calling the method.

**Comment by doits** [comment]
I don't know the internals of memery and how caching is implemented, but doesn't the overriden/prepended method get passed the evaluated arguments?

E.g. (very simplified):

```rb
def test_method(locale: I18n.locale)
  locale
end

prepend(Module.new do
  def test_method(**kwargs)
    kwargs[:locale] # should be evaluated at this point, cache based on this information?
  end
end)
```

But maybe memery does the caching completely different?

**Comment by doits** [comment]
I think I was wrong with my statement above, please feel free to ignore it :-) So indeed it seems not to be possible to do it this way.

**Comment by tycooon** [comment]
Yep, that doesn't work like that. Closing the issue for now 👍
